### ISSUE TITLE
Camera doesnt work with message Scene mode override lists asks for fixed focus on a device with focuser but not calibrated for infinity focus

### ISSUE THREAD

**Issue by HighwayStar** [HighwayStar/android_device_xiaomi_mocha#4]
This can be fixed by reverting commit 
176e4c253a63d581af6b21f3182d71b3026ef516  Camera1: Validate scene mode override AF mode

in frameworks/av

Searching for way to fix it in device tree.

**Comment by Nihhaar** [comment]
https://gitlab.com/aosplus/device_moto_shamu/commit/c254a34a5eaa075b892317809a826d9a7b5ae170?view=parallel

Works for our device tree if we want to calibrate focus.

**Comment by HighwayStar** [comment]
fixed in device tree by a639fa129cde142b566466e09f3079535f26768f , thanks to @arttttt
